/**
 * Navagraha Śānti reference table (Module 1 — Remedial Engine).
 *
 * Classical Vedic remedial data for each of the nine grahas: bīja mantra,
 * japa-saṅkhyā, samidhā (homa wood), ratna (gem), metal, daan (donation)
 * items, presiding deity and the weekday for the remedy. These are the
 * standard śānti prescriptions; refine the figures against the Surya
 * Panchanga 2083 (pp. 58–59) source if any differ.
 */

export interface GrahaShanti {
  key: string;
  nameNe: string;
  nameEn: string;
  symbol: string;
  /** Weekday best suited for the graha's remedy. */
  vaaraNe: string;
  vaaraEn: string;
  colorNe: string;
  colorEn: string;
  /** Representative swatch colour (works on light + dark). */
  colorHex: string;
  beejMantra: string;
  /** Traditional japa count for the bīja mantra. Kali Yuga count is japa × 4. */
  japa: number;
  /** Longer Vedic (graha) mantra, distinct from the bīja mantra. */
  vedicMantra: string;
  samidhaNe: string;
  samidhaEn: string;
  gemNe: string;
  gemEn: string;
  metalNe: string;
  metalEn: string;
  /** Donation (daan) items in Nepali. */
  daan: string[];
  daanEn: string[];
  adhidevataNe: string;
  adhidevataEn: string;
  /** Secondary/co-presiding deity (pratyadhidevata). */
  pratyadhidevataNe: string;
  pratyadhidevataEn: string;
  /** Direction associated with the graha, used for facing during the remedy. */
  dishaNe: string;
  dishaEn: string;
  /** Auspicious time of day for the remedy (in addition to the weekday). */
  shubhSamayaNe: string;
  shubhSamayaEn: string;
  /** 3×3 ank yantra (numerological magic square), row-major, 9 cells. */
  yantraGrid: [number, number, number, number, number, number, number, number, number];
  /** Deity/deities the remedy's puja is offered to (distinct from adhidevata/pratyadhidevata). */
  poojaNe: string;
  poojaEn: string;
  /** Short tantrik-style namaskara mantra, distinct from the bīja mantra. */
  tantrikMantra: string;
  /** Classical one-verse stotram for the graha. */
  stotram: string;
  /** Gem-wearing instructions: weight (ratti), day/nakshatra, metal, finger. */
  gemDetailNe: string;
  gemDetailEn: string;
  /** One-line note on the affliction this śānti addresses. */
  remedyNe: string;
  remedyEn: string;
}

export const NAVAGRAHA_SHANTI: GrahaShanti[] = [
  {
    key: "sun",
    nameNe: "सूर्य",
    nameEn: "Sun",
    symbol: "",
    vaaraNe: "आइतबार",
    vaaraEn: "Sunday",
    colorNe: "रातो",
    colorEn: "Red",
    colorHex: "#e23b3b",
    beejMantra: "ॐ ह्रां ह्रीं ह्रौं सः सूर्याय नमः",
    japa: 7000,
    vedicMantra:
      "ॐ आ कृष्णेन रजसा वर्तमानो निवेशयन्नमृतं मर्त्यञ्च। हिरण्ययेन सविता रथेना देवो याति भुवनानि पश्यन्॥",
    samidhaNe: "आक (मदार)",
    samidhaEn: "Arka / Calotropis",
    gemNe: "माणिक्य",
    gemEn: "Ruby",
    metalNe: "तामा",
    metalEn: "Copper",
    daan: ["रातो कपडा", "सुन", "तामा", "माणिक्य", "गहुँ", "कमलको फूल", "दुधुनी गाई", "मुसुरो", "रक्तचन्दन", "करवीरको फूल", "गुड"],
    daanEn: ["Red cloth", "Gold", "Copper", "Ruby", "Wheat", "Lotus flower", "A milk-giving cow", "Red lentils", "Red sandalwood", "Oleander flower", "Jaggery"],
    adhidevataNe: "शिव / अग्नि",
    adhidevataEn: "Shiva / Agni",
    pratyadhidevataNe: "रुद्र",
    pratyadhidevataEn: "Rudra",
    dishaNe: "पूर्व",
    dishaEn: "East",
    shubhSamayaNe: "सूर्योदयकाल",
    shubhSamayaEn: "At sunrise",
    yantraGrid: [6, 1, 8, 7, 5, 3, 2, 9, 4],
    poojaNe: "शिवपूजा / सूर्यपूजा",
    poojaEn: "Shiva Puja / Surya Puja",
    tantrikMantra: "ॐ घृणिः सूर्याय नमः।",
    stotram: "जपाकुसुमसंकाशं काश्यपेयं महाद्युतिम्। तमोऽरिं सर्वपापघ्नं प्रणतोऽस्मि दिवाकरम्॥",
    gemDetailNe: "माणिक्य १, ५ वा ९ रतिको, रवि पुष्य योग वा आइतबार बिहान तामा/सुनको औँठीमा अनामिका (साहिँली) औँलामा लगाउने।",
    gemDetailEn: "Ruby of 1, 5 or 9 ratti, worn during Ravi Pushya Yoga or on Sunday morning, in a copper/gold ring on the ring finger.",
    remedyNe: "आत्मबल, पिता, स्वास्थ्य र पदप्रतिष्ठाको पीडा शान्त गर्न।",
    remedyEn: "To ease afflictions of self-confidence, father, health and status.",
  },
  {
    key: "moon",
    nameNe: "चन्द्र",
    nameEn: "Moon",
    symbol: "",
    vaaraNe: "सोमबार",
    vaaraEn: "Monday",
    colorNe: "सेतो",
    colorEn: "White",
    colorHex: "#cfd6e6",
    beejMantra: "ॐ श्रां श्रीं श्रौं सः चन्द्राय नमः",
    japa: 11000,
    vedicMantra:
      "ॐ इमं देवा असपत्नं सुवध्वं महते क्षत्राय महते ज्येष्ठाय महते जानराज्यायेन्द्रस्येन्द्रियाय। इमममुष्य पुत्रममुष्यै पुत्रमस्यै विश एष वोऽमी राजा सोमोऽस्माकं ब्राह्मणानां राजा॥",
    samidhaNe: "पलाश (ढाक)",
    samidhaEn: "Palasha / Butea",
    gemNe: "मोती",
    gemEn: "Pearl",
    metalNe: "चाँदी",
    metalEn: "Silver",
    daan: ["सेतो कपडा", "चाँदी", "मोती", "चामल", "दूध", "दही", "मिश्री", "सेतो चन्दन", "सेतो फूल", "शंख", "सेतो गाई"],
    daanEn: ["White cloth", "Silver", "Pearl", "Rice", "Milk", "Curd", "Sugar candy", "White sandalwood", "White flower", "Conch shell", "A white cow"],
    adhidevataNe: "पार्वती / जल",
    adhidevataEn: "Parvati / Jala (Water)",
    pratyadhidevataNe: "गौरी",
    pratyadhidevataEn: "Gauri",
    dishaNe: "वायव्य",
    dishaEn: "North-West",
    shubhSamayaNe: "सन्ध्याकाल वा रात्रि",
    shubhSamayaEn: "In the evening or at night",
    yantraGrid: [7, 2, 9, 8, 6, 4, 3, 10, 5],
    poojaNe: "गौरी (पार्वती) पूजा / शिवपूजा",
    poojaEn: "Gauri (Parvati) Puja / Shiva Puja",
    tantrikMantra: "ॐ सोमाय नमः।",
    stotram: "दधिशङ्खतुषाराभं क्षीरोदार्णवसम्भवम्। नमामि शशिनं सोमं शम्भोर्मुकुटभूषणम्॥",
    gemDetailNe: "मोती ५, ७ वा ९ रतिको, सोमबार वा रोहिणी नक्षत्रमा चाँदीको औँठीमा कान्छी औँलामा लगाउने।",
    gemDetailEn: "Pearl of 5, 7 or 9 ratti, worn on Monday or during Rohini Nakshatra, in a silver ring on the little finger.",
    remedyNe: "मन, माता, शान्ति र भावनात्मक स्थिरताको लागि।",
    remedyEn: "For the mind, mother, peace and emotional stability.",
  },
  {
    key: "mars",
    nameNe: "मंगल",
    nameEn: "Mars",
    symbol: "",
    vaaraNe: "मंगलबार",
    vaaraEn: "Tuesday",
    colorNe: "रातो",
    colorEn: "Red",
    colorHex: "#d4452f",
    beejMantra: "ॐ क्रां क्रीं क्रौं सः भौमाय नमः",
    japa: 10000,
    vedicMantra: "ॐ अग्निर्मूर्धा दिवः ककुत्पतिः पृथिव्या अयम्। अपां रेतांसि जिन्वति॥",
    samidhaNe: "खैर",
    samidhaEn: "Khadira / Acacia",
    gemNe: "मूँगा",
    gemEn: "Red Coral",
    metalNe: "तामा",
    metalEn: "Copper",
    daan: ["रातो कपडा", "तामा", "मुङ्गा", "मसुरोको दाल", "गुड", "रातो चन्दन", "कस्तुरी", "सिन्दूर", "रातो साँढे"],
    daanEn: ["Red cloth", "Copper", "Red coral", "Red lentils", "Jaggery", "Red sandalwood", "Musk", "Vermilion", "A red bull"],
    adhidevataNe: "स्कन्द (कार्तिकेय) / पृथ्वी",
    adhidevataEn: "Skanda (Kartikeya) / Prithvi (Earth)",
    pratyadhidevataNe: "क्षेत्रपाल / कार्तिकेय (हनुमानजी)",
    pratyadhidevataEn: "Kshetrapala / Kartikeya (Hanuman)",
    dishaNe: "दक्षिण",
    dishaEn: "South",
    shubhSamayaNe: "प्रातः सूर्योदय पछि",
    shubhSamayaEn: "Morning, after sunrise",
    yantraGrid: [8, 3, 10, 9, 7, 5, 4, 11, 6],
    poojaNe: "हनुमान पूजा / कार्तिकेय पूजा / गणेश पूजा",
    poojaEn: "Hanuman Puja / Kartikeya Puja / Ganesha Puja",
    tantrikMantra: "ॐ अं अङ्गारकाय नमः।",
    stotram: "धरणीगर्भसम्भूतं विद्युत्कान्तिसमप्रभम्। कुमारं शक्तिहस्तं च मङ्गलं प्रणमाम्यहम्॥",
    gemDetailNe: "मूँगा ५, ७ वा ९ रतिको, मङ्गलबार वा चित्रा नक्षत्रमा तामा वा सुनको औँठीमा अनामिका (साहिँली) औँलामा लगाउने।",
    gemDetailEn: "Red Coral of 5, 7 or 9 ratti, worn on Tuesday or during Chitra Nakshatra, in a copper or gold ring on the ring finger.",
    remedyNe: "रक्त, ऋण, भाइ, साहस र मंगल दोष शान्त गर्न।",
    remedyEn: "To ease blood, debt, siblings, courage and Mangal dosha.",
  },
  {
    key: "mercury",
    nameNe: "बुध",
    nameEn: "Mercury",
    symbol: "",
    vaaraNe: "बुधबार",
    vaaraEn: "Wednesday",
    colorNe: "हरियो",
    colorEn: "Green",
    colorHex: "#2fae6a",
    beejMantra: "ॐ ब्रां ब्रीं ब्रौं सः बुधाय नमः",
    japa: 9000,
    vedicMantra:
      "ॐ उद्बुध्यस्वाग्ने प्रति जागृहि त्वमिष्टापूर्ते सं सृजेथामयं च। अस्मिन्त्सधस्थे अध्युत्तरस्मिन् विश्वे देवा यजमानश्च सीदत॥",
    samidhaNe: "अपामार्ग (दतिवन)",
    samidhaEn: "Apamarga / Achyranthes",
    gemNe: "पन्ना",
    gemEn: "Emerald",
    metalNe: "काँसा",
    metalEn: "Bronze",
    daan: ["हरियो कपडा", "काँसको बर्तन", "पन्ना", "मूगको दाल", "घिउ", "काँचो फलफूल", "हरियो सागपात", "सुगा", "सुन"],
    daanEn: ["Green cloth", "Bronze vessel", "Emerald", "Green gram", "Ghee", "Raw fruit", "Green leafy vegetables", "A parrot", "Gold"],
    adhidevataNe: "विष्णु",
    adhidevataEn: "Vishnu",
    pratyadhidevataNe: "नारायण",
    pratyadhidevataEn: "Narayana",
    dishaNe: "उत्तर",
    dishaEn: "North",
    shubhSamayaNe: "प्रातःकाल",
    shubhSamayaEn: "In the morning",
    yantraGrid: [9, 4, 11, 10, 8, 6, 5, 12, 7],
    poojaNe: "विष्णु पूजा / दुर्गा पूजा",
    poojaEn: "Vishnu Puja / Durga Puja",
    tantrikMantra: "ॐ बुं बुधाय नमः।",
    stotram: "प्रियङ्गुकलिकाश्यामं रूपेणाप्रतिमं बुधम्। सौम्यं सौम्यगुणोपेतं तं बुधं प्रणमाम्यहम्॥",
    gemDetailNe: "पन्ना ३, ५ वा ७ रतिको, बुधबार वा ज्येष्ठा नक्षत्रमा काँस/सुनको औँठीमा कान्छी औँलामा लगाउने।",
    gemDetailEn: "Emerald of 3, 5 or 7 ratti, worn on Wednesday or during Jyeshtha Nakshatra, in a bronze/gold ring on the little finger.",
    remedyNe: "बुद्धि, वाणी, व्यापार र शिक्षा सुधारका लागि।",
    remedyEn: "To improve intellect, speech, business and education.",
  },
  {
    key: "jupiter",
    nameNe: "गुरु (बृहस्पति)",
    nameEn: "Jupiter",
    symbol: "",
    vaaraNe: "बिहिबार",
    vaaraEn: "Thursday",
    colorNe: "पहेँलो",
    colorEn: "Yellow",
    colorHex: "#e0a92e",
    beejMantra: "ॐ ग्रां ग्रीं ग्रौं सः गुरवे नमः",
    japa: 19000,
    vedicMantra:
      "ॐ बृहस्पते अति यदर्यो अर्हाद् द्युमद्विभाति क्रतुमज्जनेषु। यद्दीदयच्छवस ऋतप्रजात तदस्मासु द्रविणं धेहि चित्रम्॥",
    samidhaNe: "पीपल",
    samidhaEn: "Pippala / Ashwattha",
    gemNe: "पुखराज",
    gemEn: "Yellow Sapphire",
    metalNe: "सुन",
    metalEn: "Gold",
    daan: ["पहेंलो कपडा", "सुन", "पुखराज", "चनाको दाल", "हलेदो (हल्दी)", "पहेंलो फूल", "केसर", "पाकेको केरा", "पहेंलो गाई"],
    daanEn: ["Yellow cloth", "Gold", "Yellow sapphire", "Chickpea lentils", "Turmeric", "Yellow flower", "Saffron", "Ripe banana", "A yellow (fawn) cow"],
    adhidevataNe: "ब्रह्मा / इन्द्र",
    adhidevataEn: "Brahma / Indra",
    pratyadhidevataNe: "इन्द्र",
    pratyadhidevataEn: "Indra",
    dishaNe: "ईशान",
    dishaEn: "North-East",
    shubhSamayaNe: "प्रातःकाल",
    shubhSamayaEn: "In the morning",
    yantraGrid: [10, 5, 12, 11, 9, 7, 6, 13, 8],
    poojaNe: "ब्रह्मा पूजा / विष्णु पूजा",
    poojaEn: "Brahma Puja / Vishnu Puja",
    tantrikMantra: "ॐ बृं बृहस्पतये नमः।",
    stotram: "देवानां च ऋषीणां च गुरुं काञ्चनसन्निभम्। बुद्धिभूतं त्रिलोकेशं तं नमामि बृहस्पतिम्॥",
    gemDetailNe: "पुखराज ५, ७ वा ९ रतिको, बिहीबार वा पुष्य नक्षत्रमा सुनको औँठीमा तर्जनी (चोरे) औँलामा लगाउने।",
    gemDetailEn: "Yellow Sapphire of 5, 7 or 9 ratti, worn on Thursday or during Pushya Nakshatra, in a gold ring on the index finger.",
    remedyNe: "ज्ञान, सन्तान, विवाह र धन-धर्मको शुभताका लागि।",
    remedyEn: "For knowledge, children, marriage and prosperity of wealth & dharma.",
  },
  {
    key: "venus",
    nameNe: "शुक्र",
    nameEn: "Venus",
    symbol: "",
    vaaraNe: "शुक्रबार",
    vaaraEn: "Friday",
    colorNe: "सेतो / चहकिलो",
    colorEn: "White / bright",
    colorHex: "#d9c7e8",
    beejMantra: "ॐ द्रां द्रीं द्रौं सः शुक्राय नमः",
    japa: 16000,
    vedicMantra:
      "ॐ अन्नात्परिस्रुतो रसं ब्रह्मणा व्यपिबत् क्षत्रं पयः सोमं प्रजापतिः। ऋतेन सत्यमिन्द्रियं विपानं शुक्रमन्धस इन्द्रस्येन्द्रियमिदं पयोऽमृतं मधु॥",
    samidhaNe: "गूलर (डुम्री)",
    samidhaEn: "Audumbara / Cluster Fig",
    gemNe: "हीरा",
    gemEn: "Diamond",
    metalNe: "चाँदी",
    metalEn: "Silver",
    daan: ["सेतो कपडा", "चाँदी", "हिरा", "सेतो तिल", "खाँड/मिश्री", "घिउ", "सुगन्ध (अत्तर)", "सेतो घोडा", "दही", "सेतो गाई"],
    daanEn: ["White cloth", "Silver", "Diamond", "White sesame", "Sugar/sugar candy", "Ghee", "Perfume", "A white horse", "Curd", "A white cow"],
    adhidevataNe: "इन्द्राणी / लक्ष्मी",
    adhidevataEn: "Indrani / Lakshmi",
    pratyadhidevataNe: "मरुत्वान् (लक्ष्मी)",
    pratyadhidevataEn: "Marutvan (Lakshmi)",
    dishaNe: "आग्नेय",
    dishaEn: "South-East",
    shubhSamayaNe: "सूर्योदयकाल",
    shubhSamayaEn: "At sunrise",
    yantraGrid: [11, 6, 13, 12, 10, 8, 7, 14, 9],
    poojaNe: "लक्ष्मी पूजा / इन्द्राणी पूजा",
    poojaEn: "Lakshmi Puja / Indrani Puja",
    tantrikMantra: "ॐ शुं शुक्राय नमः।",
    stotram: "हिमकुन्दमृणालाभं दैत्यानां परमं गुरुम्। सर्वशास्त्रप्रवक्तारं भार्गवं प्रणमाम्यहम्॥",
    gemDetailNe: "हीरा वा ओपल ०.५, १ वा २ रतिको, शुक्रबार वा भरणी नक्षत्रमा चाँदी/प्लाटिनमको औँठीमा मध्यमा वा कान्छी औँलामा लगाउने।",
    gemDetailEn: "Diamond or Opal of 0.5, 1 or 2 ratti, worn on Friday or during Bharani Nakshatra, in a silver/platinum ring on the middle or little finger.",
    remedyNe: "प्रेम, वैवाहिक सुख, सौन्दर्य र भोग-ऐश्वर्यका लागि।",
    remedyEn: "For love, marital happiness, beauty and comforts & luxury.",
  },
  {
    key: "saturn",
    nameNe: "शनि",
    nameEn: "Saturn",
    symbol: "",
    vaaraNe: "शनिबार",
    vaaraEn: "Saturday",
    colorNe: "कालो / गाढा नीलो",
    colorEn: "Black / dark blue",
    colorHex: "#3a4a6b",
    beejMantra: "ॐ प्रां प्रीं प्रौं सः शनैश्चराय नमः",
    japa: 23000,
    vedicMantra: "ॐ शं नो देवीरभिष्टय आपो भवन्तु पीतये। शं योरभि स्रवन्तु नः॥",
    samidhaNe: "शमी (सजिवन)",
    samidhaEn: "Shami / Prosopis",
    gemNe: "नीलम",
    gemEn: "Blue Sapphire",
    metalNe: "फलाम",
    metalEn: "Iron",
    daan: ["कालो कपडा", "फलाम", "तोरीको तेल", "नीलम", "मासको दाल", "कालो तिल", "छाता", "जुत्ता", "कालो बोका/भैंसी"],
    daanEn: ["Black cloth", "Iron", "Mustard oil", "Blue sapphire", "Black gram", "Black sesame", "An umbrella", "Shoes", "A black goat/buffalo"],
    adhidevataNe: "यम / प्रजापति",
    adhidevataEn: "Yama / Prajapati",
    pratyadhidevataNe: "प्रजापति (भैरव)",
    pratyadhidevataEn: "Prajapati (Bhairava)",
    dishaNe: "पश्चिम",
    dishaEn: "West",
    shubhSamayaNe: "सन्ध्याकाल (साँझ)",
    shubhSamayaEn: "In the evening",
    yantraGrid: [12, 7, 14, 13, 11, 9, 8, 15, 10],
    poojaNe: "हनुमान पूजा / भैरव पूजा / यम पूजा",
    poojaEn: "Hanuman Puja / Bhairava Puja / Yama Puja",
    tantrikMantra: "ॐ शं शनैश्चराय नमः।",
    stotram: "नीलाञ्जनसमाभासं रविपुत्रं यमाग्रजम्। छायामार्तण्डसम्भूतं तं नमामि शनैश्चरम्॥",
    gemDetailNe: "नीलम ४, ६ वा ७ रतिको, शनिबार वा अनुराधा नक्षत्रमा फलाम/पञ्चधातुको औँठीमा मध्यमा (माझि) औँलामा लगाउने।",
    gemDetailEn: "Blue Sapphire of 4, 6 or 7 ratti, worn on Saturday or during Anuradha Nakshatra, in an iron/panchadhatu ring on the middle finger.",
    remedyNe: "साढेसाती, ढैया, बाधा, रोग र कर्मफल शान्त गर्न।",
    remedyEn: "To ease Sade-Sati, Dhaiya, obstacles, illness and karmic results.",
  },
  {
    key: "rahu",
    nameNe: "राहु",
    nameEn: "Rahu",
    symbol: "",
    vaaraNe: "शनिबार",
    vaaraEn: "Saturday",
    colorNe: "धुम्रो / नीलो",
    colorEn: "Smoky / blue",
    colorHex: "#6b6f7a",
    beejMantra: "ॐ भ्रां भ्रीं भ्रौं सः राहवे नमः",
    japa: 18000,
    vedicMantra: "ॐ कया नश्चित्र आ भुवदूती सदावृधः सखा। कया शचिष्ठया वृता॥",
    samidhaNe: "दुबो",
    samidhaEn: "Durva grass",
    gemNe: "गोमेद",
    gemEn: "Hessonite",
    metalNe: "सिसा (अष्टधातु)",
    metalEn: "Lead (Ashtadhatu)",
    daan: ["नीलो/कालो कपडा", "सिसा", "गोमेद", "तोरी", "सप्तधान्य", "कालो तिल", "नरिवल", "कम्बल"],
    daanEn: ["Blue/black cloth", "Lead", "Hessonite", "Mustard", "Seven grains (saptadhanya)", "Black sesame", "Coconut", "Blanket"],
    adhidevataNe: "दुर्गा / सर्प",
    adhidevataEn: "Durga / Sarpa (Serpent)",
    pratyadhidevataNe: "सर्प (सरस्वती)",
    pratyadhidevataEn: "Sarpa (Saraswati)",
    dishaNe: "नैऋत्य",
    dishaEn: "South-West",
    shubhSamayaNe: "रात्रि वा सन्ध्याकाल",
    shubhSamayaEn: "At night or in the evening",
    yantraGrid: [13, 8, 15, 14, 12, 10, 9, 16, 11],
    poojaNe: "सरस्वती पूजा / दुर्गा पूजा / नाग पूजा",
    poojaEn: "Saraswati Puja / Durga Puja / Naga Puja",
    tantrikMantra: "ॐ रां राहवे नमः।",
    stotram: "अर्धकायं महावीर्यं चन्द्रादित्यविमर्दनम्। सिंहिकागर्भसम्भूतं तं राहुं प्रणमाम्यहम्॥",
    gemDetailNe: "गोमेद ६, ७ वा ९ रतिको, शनिबार वा स्वाती नक्षत्रमा अष्टधातु/चाँदीको औँठीमा मध्यमा औँलामा लगाउने।",
    gemDetailEn: "Hessonite of 6, 7 or 9 ratti, worn on Saturday or during Swati Nakshatra, in an ashtadhatu/silver ring on the middle finger.",
    remedyNe: "भ्रम, अकस्मात बाधा, मानसिक तनाव र राहु दोष शान्त गर्न।",
    remedyEn: "To ease confusion, sudden obstacles, mental stress and Rahu dosha.",
  },
  {
    key: "ketu",
    nameNe: "केतु",
    nameEn: "Ketu",
    symbol: "",
    vaaraNe: "मंगलबार",
    vaaraEn: "Tuesday",
    colorNe: "धुम्रो / खैरो",
    colorEn: "Smoky / brown",
    colorHex: "#8a7a5c",
    beejMantra: "ॐ स्रां स्रीं स्रौं सः केतवे नमः",
    japa: 17000,
    vedicMantra: "ॐ केतुं कृण्वन्नकेतवे पेशो मर्या अपेशसे। समुषद्भिरजायथाः॥",
    samidhaNe: "कुश",
    samidhaEn: "Kusha grass",
    gemNe: "लहसुनिया",
    gemEn: "Cat's Eye",
    metalNe: "अष्टधातु",
    metalEn: "Ashtadhatu (eight-metal alloy)",
    daan: ["दुई रङ्गे कम्बल", "कालो-सेतो तिल", "लहसुनिया", "काँस", "ध्वजा", "चाकू/शस्त्र", "कागती", "कस्तुरी"],
    daanEn: ["Two-colored (piebald) blanket", "Black-and-white sesame", "Cat's Eye", "Bronze", "A flag", "A knife/weapon", "Lemon", "Musk"],
    adhidevataNe: "चित्रगुप्त / गणेश",
    adhidevataEn: "Chitragupta / Ganesha",
    pratyadhidevataNe: "ब्रह्मा (गणेश)",
    pratyadhidevataEn: "Brahma (Ganesha)",
    dishaNe: "ऊर्ध्व",
    dishaEn: "Upward (central axis)",
    shubhSamayaNe: "रात्रि वा सन्ध्याकाल",
    shubhSamayaEn: "At night or in the evening",
    yantraGrid: [14, 9, 16, 15, 13, 11, 10, 17, 12],
    poojaNe: "गणेश पूजा / चित्रगुप्त पूजा",
    poojaEn: "Ganesha Puja / Chitragupta Puja",
    tantrikMantra: "ॐ कें केतवे नमः।",
    stotram: "पलाशपुष्पसंकाशं तारकाग्रहमस्तकम्। रौद्रं रौद्रात्मकं घोरं तं केतुं प्रणमाम्यहम्॥",
    gemDetailNe: "लहसुनिया ५, ७ वा ८ रतिको, मङ्गलबार/शनिबार वा अश्विनी नक्षत्रमा पञ्चधातु/चाँदीको औँठीमा कनिष्ठिका वा अनामिका औँलामा लगाउने।",
    gemDetailEn: "Cat's Eye of 5, 7 or 8 ratti, worn on Tuesday/Saturday or during Ashwini Nakshatra, in a panchadhatu/silver ring on the little or ring finger.",
    remedyNe: "मोक्ष-बाधा, रहस्यमय रोग र केतु दोष शान्त गर्न।",
    remedyEn: "To ease obstacles to moksha, mysterious illness and Ketu dosha.",
  },
];

export function getGrahaShanti(key: string): GrahaShanti | undefined {
  return NAVAGRAHA_SHANTI.find((g) => g.key === key);
}
