/**
 * Every diagram id a Learn article can name. The website draws the first group
 * with its own SVG/3D components; the app draws all of them (the last few are
 * app-only widgets). Each app keeps its own registry of components keyed by these.
 */
export const DIAGRAM_IDS = [
  "earth-orbit",
  "earth-rotation",
  "sun-earth-moon",
  "ecliptic-belt",
  "declination-year",
  "ritu-wheel",
  "lunar-solar-gap",
  "circumpolar-sky",
  "retrograde-loop",
  "manda-shighra",
  "paksha-strip",
  "two-zero-points",
  "zodiac-belt-width",
  "ecliptic-equator-cross",
  "hora-weekday-cycle",
  "year-length-ladder",
  "gregorian-jump",
  "eclipse-season-window",
  "sun-ray-angle",
  "sidereal-solar-day",
  "day-length-hour-angle",
  "moonrise-slip",
  "sunrise-samples-tithi",
  "tithi-across-zones",
  "solar-month-lengths",
  "two-systems",
  "calendar-hierarchy",
  "ayanamsha-wheel",
  "equinox-precession",
  "precession-cone",
  "precession-sky",
  "tithi-elongation",
  "moon-phases",
  "moon-orbit-tilt",
  "adhik-maas",
  "sunrise-vriddhi",
  "sunrise-kshaya",
  "lunar-eclipse",
  "solar-eclipse",
  "table-rashi",
  "table-graha",
  "table-nakshatra",
  "table-tithi",
  "table-yoga",
  "table-karana",
  "hora-live",
  "server-pipeline",
  "computation-reference",
] as const;

export type DiagramId = (typeof DIAGRAM_IDS)[number];
