// URL golden calls for apps/mobile/lib/api.ts. Signature-specific; keep the
// arguments the screens and the offline pack use.
import * as api from "@/lib/api";
const L = [undefined, { city_id: 1283240, timezone: "Asia/Kathmandu" }, { lat: 27.7, lon: 85.3, timezone: "Asia/Kathmandu" }, { city: "Pokhara", lat: 28.2, lon: 83.98 }] as any[];
const moment = { inputEra: "bs", year: 2050, month: 5, day: 12, clock: "06:30" } as any;
const a: any = api;
export const calls: [string, () => unknown][] = [];
const add = (n: string, f: () => unknown) => calls.push([n, f]);
L.forEach((loc, i) => {
  const s = `#${i}`;
  add("fetchNearestCity" + s, () => a.fetchNearestCity(27.7, 85.3, "NP"));
  add("searchCities" + s, () => a.searchCities("kath", 15, "NP"));
  add("fetchMonthCalendar" + s, () => a.fetchMonthCalendar(2083, 6, loc));
  add("fetchMonthCalendar-ad" + s, () => a.fetchMonthCalendar(2026, 10, loc, { era: "ad" }));
  add("fetchYearWheelCalendar" + s, () => a.fetchYearWheelCalendar(2083, loc));
  add("fetchPanchanga" + s, () => a.fetchPanchanga("2026-10-10", "ad", loc));
  add("fetchTodayPanchanga" + s, () => a.fetchTodayPanchanga(loc));
  add("fetchPanchangaAtTime" + s, () => a.fetchPanchangaAtTime("2026-10-10T06:30", loc, { ayanamsha: "lahiri" }));
  add("fetchCivilTimeline" + s, () => a.fetchCivilTimeline("2026-10-10", "ad", loc));
  add("fetchHolidays" + s, () => a.fetchHolidays(2083));
  add("fetchFestivals-ne" + s, () => a.fetchFestivals(2083, { language: "ne" }));
  add("fetchFestivals-en" + s, () => a.fetchFestivals(2083, { language: "en" }));
  for (const p of ["daily", "monthly"]) add("fetchRashifal-" + p + s, () => a.fetchRashifal("2026-10-10", p, loc));
  add("fetchPersonalRashifal" + s, () => a.fetchPersonalRashifal("2026-10-10", "daily", { moment, birthLat: 27.7, birthLon: 85.3, birthTz: "Asia/Kathmandu" }, loc));
  add("fetchGochar" + s, () => a.fetchGochar("2026-10-10", "ad", loc));
  add("fetchGocharIngress" + s, () => a.fetchGocharIngress("2026-04-14", "2027-04-13", loc, { level: "rashi", era: "bs" }));
  add("fetchGocharIngress-def" + s, () => a.fetchGocharIngress("2026-04-14", "2027-04-13", loc));
  add("fetchSpecialMonths" + s, () => a.fetchSpecialMonths(2083));
  add("fetchSaitMonthAll" + s, () => a.fetchSaitMonthAll(2083, 6, loc));
  add("fetchJanmaRashi" + s, () => a.fetchJanmaRashi(moment, "Asia/Kathmandu"));
  add("fetchSaitPersonalize" + s, () => a.fetchSaitPersonalize(2083, "vivah", loc, moment, "Asia/Kathmandu", "male"));
  add("fetchSait" + s, () => a.fetchSait(2083, "vivah", loc));
  add("fetchSaitDetail" + s, () => a.fetchSaitDetail(2083, "vivah", loc, ["b", "a"], "janma"));
  add("fetchSaitDetail-plain" + s, () => a.fetchSaitDetail(2083, "vivah", loc));
  add("fetchGrahaSthiti" + s, () => a.fetchGrahaSthiti("2026-10-10", loc, "ad"));
  add("fetchGrahaAstaYear" + s, () => a.fetchGrahaAstaYear(2083, loc, "bs"));
  add("fetchGrahaVakriYear" + s, () => a.fetchGrahaVakriYear(2083, loc, "bs"));
  add("fetchEclipseYear-solar" + s, () => a.fetchEclipseYear("solar", 2083, loc, "bs"));
  add("fetchEclipseYear-lunar-ad" + s, () => a.fetchEclipseYear("lunar", 2026, loc, "ad"));
  add("fetchPanchakYear" + s, () => a.fetchPanchakYear(2083, loc, "bs"));
  add("fetchElementDay" + s, () => a.fetchElementDay("tithi", "2026-10-10", loc));
  add("fetchYearSunTimes" + s, () => a.fetchYearSunTimes(2083, "bs", loc));
  add("fetchElementSpans" + s, () => a.fetchElementSpans("tithi", { era: "bs", year: 2083, month: 6 }, loc));
  add("fetchTropicalSeasons" + s, () => a.fetchTropicalSeasons(loc));
  add("fetchVimshottari" + s, () => a.fetchVimshottari(moment, loc, { ayanamsha: "lahiri", cycles: 2 }));
  add("fetchShadbala" + s, () => a.fetchShadbala(moment, loc));
  add("fetchKundaliDetail" + s, () => a.fetchKundaliDetail(moment, loc, { ayanamsha: "raman" }));
  add("streamKundaliReport" + s, () => a.streamKundaliReport(moment, loc, { lang: "ne" }, () => {}));
});
add("fetchAdToBs", () => a.fetchAdToBs("2026-10-10"));
add("fetchBsToAd", () => a.fetchBsToAd("2083-06-24"));
add("fetchYogaReference", () => a.fetchYogaReference());
add("fetchBhavaReference", () => a.fetchBhavaReference());
add("fetchDashaChildren", () => a.fetchDashaChildren("Sun", "2020-01-01", "2026-01-01", "vimshottari"));
add("fetchKundaliMilan", () => a.fetchKundaliMilan({ moment, location: { city_id: 1 } }, { moment, location: { lat: 1, lon: 2 } }, { lang: "ne" }));
add("fetchVastuSketch", () => a.fetchVastuSketch({ plot: { width: 10, depth: 12 } }));
add("fetchPatroCapabilities", () => a.fetchPatroCapabilities());
