#!/usr/bin/env python3
"""Map every Rigveda Rishi/Devata/Chhanda string to Devanagari.

Reads data/rigveda_authorship.json and writes the lookup the Nepali UI uses.
English stays the stored value; this file is only the Nepali-script form.

    python3 scripts/build_sukta_devanagari.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUTHORSHIP = ROOT / "data/rigveda_authorship.json"
OUT = ROOT.parent / "dhakal-patro/src/lib/sukta-attribution-ne.json"

# Longer phrases first so "Gayatri Mantra" is not split into two words.
PHRASES: list[tuple[str, str]] = [
    ("Gayatri Mantra", "गायत्रीमन्त्र"),
    ("Armor, Bow, Weapons", "कवच, धनु, आयुध"),
    ("Frogs / Rain Invocations", "मण्डूक / वर्षावाहन"),
    ("Vasistha Clan", "वसिष्ठवंश"),
    ("Gambler's Lament", "अक्षकन्द"),
    ("Hymn of Creation", "सृष्टिसूक्त"),
    ("Hymn of Unity", "संज्ञानसूक्त"),
    ("Sacrificial Post", "यूप"),
    ("Arani Churning", "अरणिमन्थन"),
    ("Funeral Rites", "अन्त्येष्टि"),
    ("Cosmic Being", "विराट्पुरुष"),
    ("Cosmic Speech", "दिव्यवाक्"),
    ("Apri Deities", "आप्रीदेवता"),
    ("Apri Hymn", "आप्रीसूक्त"),
    ("Ritu Devatas", "ऋतुदेवता"),
    ("Soma Pavamana", "सोमपवमान"),
    ("Vaishvanara Agni", "वैश्वानर अग्नि"),
    ("Purusha Sukta", "पुरुषसूक्त"),
    ("Hiranyagarbha Sukta", "हिरण्यगर्भसूक्त"),
    ("Devi Sukta", "देवीसूक्त"),
    ("Vak Sukta", "वाक्सूक्त"),
    ("Nasadiya Sukta", "नासदीयसूक्त"),
    ("Samjnana Sukta", "संज्ञानसूक्त"),
    ("Asya Vamiya Sukta", "अस्यवामीयसूक्त"),
    ("Rain Invocations", "वर्षावाहन"),
    ("etc.", "इत्यादि"),
]

WORDS: dict[str, str] = {
    "Abhivarta": "अभिवर्त",
    "Aditi": "अदिति",
    "Adityas": "आदित्याः",
    "Agastya": "अगस्त्य",
    "Aghamarshana": "अघमर्षण",
    "Agni": "अग्नि",
    "Agni-Soma": "अग्निसोम",
    "Aham": "अहम्",
    "Ailusha": "ऐलूष",
    "Aindra": "ऐन्द्र",
    "Ajigarti": "आजीगर्ति",
    "Aksha": "अक्ष",
    "Amahiu": "अमहियु",
    "Ambhrini": "आम्भृणी",
    "Amhomuch": "अम्होमुच्",
    "Ancestors": "पितरः",
    "Angirasa": "आङ्गिरस",
    "Anna": "अन्न",
    "Anumati": "अनुमति",
    "Anushtup": "अनुष्टुप्",
    "Ap": "अप्",
    "Apah": "आपः",
    "Apam": "अपाम्",
    "Apri": "आप्री",
    "Apratiratha": "अप्रतिरथ",
    "Aptya": "आप्त्य",
    "Arani": "अरणि",
    "Archanas": "अर्चनस्",
    "Armor": "कवच",
    "Aruna": "अरुण",
    "Aryama": "अर्यमा",
    "Asamati": "असमति",
    "Ashva": "अश्व",
    "Ashvins": "अश्विनौ",
    "Ashtaka": "अष्टक",
    "Asita": "असित",
    "Asya": "अस्य",
    "Atishakvari": "अतिशक्वरी",
    "Atreya": "आत्रेय",
    "Atri": "अत्रि",
    "Atyashti": "अत्यष्टि",
    "Auchathya": "औचथ्य",
    "Avatsara": "अवत्सार",
    "Ayu": "आयु",
    "Bandhu": "बन्धु",
    "Barhaspatya": "बार्हस्पत्य",
    "Barhata": "बार्हत",
    "Being": "भूत",
    "Bhalandana": "भालन्दन",
    "Bharadvaja": "भरद्वाज",
    "Bharadvaji": "भारद्वाजी",
    "Bharga": "भर्ग",
    "Bhargava": "भार्गव",
    "Bhauma": "भौम",
    "Bhavayavya": "भावयव्य",
    "Bhikshu": "भिक्षु",
    "Bhrigu": "भृगु",
    "Bindu": "बिन्दु",
    "Bow": "धनु",
    "Brahmanaspati": "ब्रह्मणस्पति",
    "Brihaspati": "बृहस्पति",
    "Brihati": "बृहती",
    "Charity": "दान",
    "Chhandas": "छन्दस्",
    "Chitramahas": "चित्रमहस्",
    "Churning": "मन्थन",
    "Clan": "वंश",
    "Cosmic": "दिव्य",
    "Creation": "सृष्टि",
    "Creator": "स्रष्टा",
    "Dadhikra": "दधिक्रा",
    "Dadhikravan": "दधिक्रावन्",
    "Dairghatamasa": "दैर्घतमस",
    "Daivodasi": "दैवोदासि",
    "Dampati": "दम्पती",
    "Danastuti": "दानस्तुति",
    "Devagana": "देवगण",
    "Devanam": "देवानाम्",
    "Devani": "देवानी",
    "Devanis": "देव्यः",
    "Devapi": "देवापि",
    "Devapi-Shantanu": "देवापिशन्तनु",
    "Devala": "देवल",
    "Devashravas": "देवश्रवस्",
    "Devata": "देवता",
    "Devatas": "देवता",
    "Devavata": "देववात",
    "Devi": "देवी",
    "Devinis": "देव्यः",
    "Dhanaka": "धनक",
    "Dhanus": "धनुस्",
    "Dharuna": "धारुण",
    "Dirghatama": "दीर्घतमा",
    "Dvipada": "द्विपदा",
    "Dyavaprithivi": "द्यावापृथिवी",
    "Ekadyu": "एकद्यु",
    "Evayamarut": "एवयामरुत्",
    "Frogs": "मण्डूक",
    "Funeral": "अन्त्येष्टि",
    "Garga": "गर्ग",
    "Gartsamada": "गार्त्समद",
    "Gathina": "गाथिन",
    "Gau": "गौ",
    "Gaupayana": "गौपायन",
    "Gauriviti": "गौरिवीति",
    "Gautama": "गौतम",
    "Gayatri": "गायत्री",
    "Ghaura": "घौर",
    "Ghrita": "घृत",
    "Gotama": "गोतम",
    "Grtsamada": "गृत्समद",
    "Hamsa": "हंस",
    "Haryata": "हर्यत",
    "Health": "आरोग्य",
    "Hiranyagarbha": "हिरण्यगर्भ",
    "Hiranyastupa": "हिरण्यस्तूप",
    "Hymn": "सूक्त",
    "Idhma": "इध्म",
    "Indra": "इन्द्र",
    "Indra-Maruts": "इन्द्रमरुतः",
    "Indra-Varuna": "इन्द्रावरुणौ",
    "Indra-Vayu": "इन्द्रवायु",
    "Indra-Vrishakapi": "इन्द्रवृषाकपि",
    "Indrabrihaspati": "इन्द्रबृहस्पति",
    "Indragni": "इन्द्राग्नी",
    "Indrasoma": "इन्द्रसोमा",
    "Indu": "इन्दु",
    "Invocations": "आह्वान",
    "Jagati": "जगती",
    "Jamadagni": "जमदग्नि",
    "Janam": "जनम्",
    "Jataveda": "जातवेद",
    "Jeta": "जेता",
    "Jnana": "ज्ञान",
    "Kakshivan": "कक्षीवान्",
    "Kakubh": "ककुभ्",
    "Kanva": "कण्व",
    "Kapinjala": "कपिज्जल",
    "Kashyapa": "कश्यप",
    "Kasyapa": "कश्यप",
    "Kata": "कट",
    "Katya": "कात्य",
    "Kavasha": "कवष",
    "Kavya": "काव्य",
    "Kings": "राजन्",
    "Kingship": "राज्य",
    "Knowledge": "ज्ञान",
    "Kshetrapati": "क्षेत्रपति",
    "Kulmalabarhisha": "कुल्मलबर्हिष",
    "Kumara": "कुमार",
    "Kurma": "कूर्म",
    "Kurusuti": "कुरुसुति",
    "Kushika": "कुशिक",
    "Kutsa": "कुत्स",
    "Lament": "विलाप",
    "Lopamudra": "लोपामुद्रा",
    "Luṣa": "लुश",
    "Madhuchhanda": "मधुच्छन्दा",
    "Madhuchhandasa": "माधुच्छन्दस",
    "Mahad": "महत्",
    "Maitravaruni": "मैत्रावरुणि",
    "Mandukas": "मण्डूक",
    "Manava": "मानव",
    "Mantra": "मन्त्र",
    "Manu": "मनु",
    "Manyu": "मन्यु",
    "Maricha": "मारीच",
    "Marriage": "विवाह",
    "Maruts": "मरुतः",
    "Mathita": "मथित",
    "Medhatithi": "मेधातिथि",
    "Mitra": "मित्र",
    "Mitra-Varuna": "मित्रावरुणौ",
    "Nabhanedishtha": "नाभानेदिष्ठ",
    "Napat": "नपात्",
    "Narada": "नारद",
    "Narashamsa": "नराशंस",
    "Narayana": "नारायण",
    "Nasadiya": "नासदीय",
    "Nipatithi": "निपातिथि",
    "Nodha": "नोधा",
    "Nrmedha": "नृमेध",
    "Oshadhis": "ओषधि",
    "Pankti": "पङ्क्ति",
    "Parameshthi": "परमेष्ठिन्",
    "Parashara": "पराशर",
    "Parjanya": "पर्जन्य",
    "Paruchhepa": "परुच्छेप",
    "Parvata": "पर्वत",
    "Paura": "पौर",
    "Pavamana": "पवमान",
    "Payu": "पायु",
    "Pitris": "पितरः",
    "Pitum": "पितु",
    "Post": "स्तम्भ",
    "Pragatha": "प्रागाथ",
    "Prajapati": "प्रजापति",
    "Prajapatya": "प्राजापत्य",
    "Praskanva": "प्रस्कण्व",
    "Prastara": "प्रस्तार",
    "Princes": "राजकुमार",
    "Prithivi": "पृथिवी",
    "Puru": "पुरु",
    "Purumitha": "पुरुमीढ",
    "Purusha": "पुरुष",
    "Pushan": "पूषा",
    "Pushtigu": "पुष्टिगु",
    "Rahugana": "राहूगण",
    "Rain": "वृष्टि",
    "Raka": "राका",
    "Rakshohani": "राक्षोघ्नी",
    "Rashtra": "राष्ट्र",
    "Rati": "रति",
    "Ratri": "रात्रि",
    "Ribhugana": "ऋभुगण",
    "Ribhus": "ऋभवः",
    "Rishabha": "ऋषभ",
    "Rishikas": "ऋषिका",
    "Rites": "विधि",
    "Rivers": "नद्यः",
    "Rjisvan": "ऋजिश्वन्",
    "Rogaghna": "रोगघ्न",
    "Romasha": "रोमशा",
    "Rshi": "ऋषि",
    "Rudra": "रुद्र",
    "Sacrificial": "याज्ञिक",
    "Sadasaspati": "सदसस्पति",
    "Sakuntadrsti": "शकुन्तदृष्टि",
    "Samjnana": "संज्ञान",
    "Samvanana": "संवनन",
    "Samyu": "सम्यु",
    "Sankha": "शङ्ख",
    "Saptarshis": "सप्तर्षि",
    "Saptavadhri": "सप्तवध्रि",
    "Sarasvati": "सरस्वती",
    "Sasarpari": "ससर्परी",
    "Satobrihati": "सतोबृहती",
    "Satyaprava": "सत्यश्रवा",
    "Saubhara": "सौभर",
    "Savita": "सविता",
    "Savitri": "सावित्री",
    "Savya": "सव्य",
    "Shachi": "शची",
    "Shaktya": "शाक्त्य",
    "Shamya": "शम्या",
    "Shaunaka": "शौनक",
    "Shunahshepa": "शुनःशेप",
    "Shutudri": "शुतुद्री",
    "Sinivali": "सिनीवाली",
    "Sobhari": "शोभरी",
    "Soma": "सोम",
    "Soma-Pusan": "सोमपूषण",
    "Soma-Rudra": "सोमरुद्र",
    "Somahuti": "सोमाहुति",
    "Speech": "वाक्",
    "Srishtigu": "सृष्टिगु",
    "Srutavit": "श्रुतवित्",
    "Suditi": "सुदीति",
    "Suhotra": "सुहोत्र",
    "Sukta": "सूक्त",
    "Surya": "सूर्य",
    "Suryaa": "सूर्या",
    "Sutambhara": "सुतम्भरा",
    "Svanaya": "स्वनय",
    "Syavasva": "श्यावाश्व",
    "Tanunapat": "तनूनपात्",
    "Trishoka": "त्रिशोक",
    "Trisiras": "त्रिशिरा",
    "Trishtup": "त्रिष्टुप्",
    "Trita": "त्रित",
    "Tvastra": "त्वाष्ट्र",
    "Ulukhala-Musala": "उलूखलमुसल",
    "Unity": "ऐक्य",
    "Usanas": "उशना",
    "Usha": "उषा",
    "Ushnih": "उष्णिक्",
    "Utkila": "उत्कील",
    "Vaishvamitra": "वैश्वामित्र",
    "Vaishvanara": "वैश्वानर",
    "Vaivasvata": "वैवस्वत",
    "Vaivasvati": "वैवस्वती",
    "Vak": "वाक्",
    "Vamadeva": "वामदेव",
    "Vamiya": "वामी",
    "Vamra": "वम्र",
    "Vana": "वन",
    "Varman": "वर्मन्",
    "Varshagira": "वर्षागिर",
    "Varuna": "वरुण",
    "Vasistha": "वसिष्ठ",
    "Vasishtha": "वसिष्ठ",
    "Vasishthas": "वसिष्ठाः",
    "Vastospati": "वास्तोष्पति",
    "Vasushruta": "वसुश्रुत",
    "Vatsa": "वत्स",
    "Vatsapri": "वत्सप्री",
    "Vayu": "वायु",
    "Vedic": "वैदिक",
    "Vena": "वेन",
    "Victory": "विजय",
    "Vihavya": "विहव्य",
    "Vimada": "विमद",
    "Vipash": "विपाश्",
    "Virat": "विराट्",
    "Virupa": "विरूप",
    "Vishaghna": "विषघ्न",
    "Vishnu": "विष्णु",
    "Vishvamanas": "विश्वमनस्",
    "Vishvamitra": "विश्वामित्र",
    "Vishvedevah": "विश्वेदेवाः",
    "Vivaha": "विवाह",
    "Vrishakapi": "वृषाकपि",
    "Water": "आपः",
    "Weapons": "आयुध",
    "Wrath": "क्रोध",
    "Yajna": "यज्ञ",
    "Yakshmanashana": "यक्ष्मनाशन",
    "Yama": "यम",
    "Yami": "यामी",
    "Yupa": "यूप",
    "Yuta": "युत",
    "asuratvam": "असुरत्वम्",
    "devanam": "देवानाम्",
    "ekam": "एकम्",
    "etc": "इत्यादि",
    "of": "",
    "s": "",
}

TOKEN_RE = re.compile(r"[A-Za-zṣ][A-Za-zṣ'’\-]*")
DIGITS = str.maketrans("0123456789", "०१२३४५६७८९")


def to_devanagari(text: str) -> str:
    for phrase, dev in PHRASES:
        text = text.replace(phrase, dev)
    missing: list[str] = []

    def repl(match: re.Match[str]) -> str:
        word = match.group(0)
        if word not in WORDS:
            missing.append(word)
            return word
        return WORDS[word]

    text = TOKEN_RE.sub(repl, text)
    text = re.sub(r"\s*/\s*", " / ", text)
    text = re.sub(r"\s{2,}", " ", text)
    text = re.sub(r"\s+([,)])", r"\1", text)
    text = re.sub(r"\(\s+", "(", text)
    if missing:
        raise SystemExit(f"Unmapped words: {sorted(set(missing))}")
    if re.search(r"[A-Za-z]", text):
        raise SystemExit(f"Latin left in: {text}")
    return text.translate(DIGITS).strip()


def main() -> None:
    authorship = json.loads(AUTHORSHIP.read_text(encoding="utf-8"))
    unique: set[str] = set()
    for entry in authorship.values():
        unique.update(entry[field] for field in ("rishi", "devata", "chhanda"))
    mapped = {text: to_devanagari(text) for text in sorted(unique)}
    OUT.write_text(json.dumps(mapped, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.name}: {len(mapped)} strings")


if __name__ == "__main__":
    main()
