#!/usr/bin/env python3
"""Precompute the samvatsara (60-year Jovian cycle) index for every patro year.

The runtime resolver walks Jupiter's longitude at each patro new year, one year
at a time out from the BS 2080 anchor. That is fine near the anchor and hopeless
far from it — a cold BBS 7144 lookup measured **14.3 s**, which on a single
worker blocks every other request for a purely decorative label.

Walking once and writing the answers down turns that into an O(1) lookup. This
does the whole range in one sequential pass (each year reuses the previous year's
Jupiter longitude), so generating ~10 000 years costs about the same as the one
deep walk it replaces.

Writes both consumers so they can never disagree:

  * ``engine/vedic/samvatsara_table.json``            (backend)
  * ``../dhakal-patro/src/lib/samvatsara-table.json`` (frontend)

Run from the repo root:
    python scripts/generate_samvatsara_table.py
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

API_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(API_ROOT))

BACKEND_OUT = API_ROOT / "engine" / "vedic" / "samvatsara_table.json"
FRONTEND_OUT = API_ROOT.parent / "dhakal-patro" / "src" / "lib" / "samvatsara-table.json"

from engine.vedic.patro_year_axis import (  # noqa: E402
    PATRO_EPHEMERIS_SIGNED_MAX,
    PATRO_EPHEMERIS_SIGNED_MIN,
)
from engine.vedic.samvatsara import (  # noqa: E402
    ANCHOR_BS_YEAR,
    ANCHOR_INDEX,
    _advance_samvatsara_index,
    _backward_samvatsara_step,
    _jupiter_longitude_at_bs_new_year,
    _rashi_ingress_delta,
)


def _next_year(year: int) -> int:
    """Step up one patro year, skipping the nonexistent year 0."""
    return 1 if year == -1 else year + 1


def _prev_year(year: int) -> int:
    return -1 if year == 1 else year - 1


def build_table(lo: int, hi: int) -> dict[int, int]:
    """Samvatsara index for every patro year in ``lo..hi``, anchored at BS 2080."""
    indices: dict[int, int] = {ANCHOR_BS_YEAR: ANCHOR_INDEX}

    # Forward from the anchor — the tuned walk with Nepal's kshaya corrections.
    idx = ANCHOR_INDEX
    year = ANCHOR_BS_YEAR
    prev_lon = _jupiter_longitude_at_bs_new_year(year)
    while year < hi:
        nxt = _next_year(year)
        cur_lon = _jupiter_longitude_at_bs_new_year(nxt)
        idx = (idx + _advance_samvatsara_index(idx, prev_lon, cur_lon)) % 60
        indices[nxt] = idx
        year, prev_lon = nxt, cur_lon

    # Backward from the anchor — invert the walk, falling back to plain
    # Jupiter-rashi progression once the tuned corrections stop being invertible
    # (below ~BS 1855, where no published almanac exists to tune against).
    idx = ANCHOR_INDEX
    year = ANCHOR_BS_YEAR
    while year > lo:
        prv = _prev_year(year)
        step = _backward_samvatsara_step(idx, prv)
        if step is None:
            step = (
                idx
                - _rashi_ingress_delta(
                    _jupiter_longitude_at_bs_new_year(prv),
                    _jupiter_longitude_at_bs_new_year(year),
                )
            ) % 60
        indices[prv] = step
        idx, year = step, prv

    return indices


def main() -> None:
    lo, hi = PATRO_EPHEMERIS_SIGNED_MIN, PATRO_EPHEMERIS_SIGNED_MAX
    print(f"walking patro years {lo}..{hi} from the BS {ANCHOR_BS_YEAR} anchor …")
    started = time.time()
    indices = build_table(lo, hi)
    elapsed = time.time() - started

    payload = {
        "_meta": {
            "description": (
                "Samvatsara (60-year Jovian cycle) index per signed patro year. "
                "Generated by scripts/generate_samvatsara_table.py — do not hand-edit."
            ),
            "anchor_bs_year": ANCHOR_BS_YEAR,
            "anchor_index": ANCHOR_INDEX,
            "min_year": lo,
            "max_year": hi,
            "count": len(indices),
        },
        # String keys: JSON object keys are strings, and negative years read
        # clearly as "-1" rather than needing a parallel offset scheme.
        "indices": {str(year): idx for year, idx in sorted(indices.items())},
    }

    for out in (BACKEND_OUT, FRONTEND_OUT):
        out.parent.mkdir(parents=True, exist_ok=True)
        with out.open("w", encoding="utf-8") as fh:
            json.dump(payload, fh, separators=(",", ":"), ensure_ascii=False)
        print(f"  wrote {out.relative_to(out.parent.parent.parent)} ({out.stat().st_size:,} bytes)")

    print(f"{len(indices):,} years in {elapsed:.1f}s")


if __name__ == "__main__":
    main()
